version: '3.8'
services:
  node_test:
    image: $IMAGE_TAG
    container_name: node_test
    ports:
      - "3001:3001"
    networks:
      - testing
    depends_on:
      - db
    tty: true
  db:
    container_name: pg_container
    image: postgres:latest
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    ports:
      - "5432:5432"
    networks:
      - testing

networks:
  testing:

